### ISSUE TITLE
Add @inherit where meaningfull

### ISSUE THREAD

**Issue by TomasVotruba** [Zenify/CodingStandard#38]
Correct

```php
final class SomeClass implements SomeInterface
{

    /**
     * {@inheritdoc}
     */
    public function someMethod()
    {
        // ...
    } 

}
```

**Comment by enumag** [comment]
@TomasVotruba Do you mean that the `{@inheritdoc}` should be required?

**Comment by TomasVotruba** [comment]
@enumag In these cases yes.

**Comment by enumag** [comment]
@TomasVotruba If you don't mind me asking, this package is not really that much Nette-related so why did you abandon it as well? Does Symfony have a better tool for this?

**Comment by TomasVotruba** [comment]
@enumag I'd be happy to explain. There are lots of Nette specific sniffs, that I cannot use.
Also, another part of sniffs is covered by php-cs-fixer.
 ([Just dropped 4,5 K lines due to these 2 reasons yesterday](https://github.com/Symplify/CodingStandard/pull/1)).

I'd like to keep this package separated, because every Zenify package uses it and many Nette-specific project.

For Symfony, I don't need these and it would be mess to develop coding standard for 2 frameworks (systems) in single repository.

**Comment by enumag** [comment]
What in this package is Nette-specific aside from tabs instead of spaces?

Also what is the benefit of using both PHP_CodeSniffer and php-cs-fixer for Symfony? It makes more sense to me to pick one and let it check everything.

Personally I tend to use pretty much the same coding standard as Symfony (except for tabs) and I'd like to have some tool for that. I'd probably update Zenify to use it as well. Can you recommend something?

**Comment by TomasVotruba** [comment]
See the PR, it's more obvious. Component docblock, switch statements, elseif, maybe some more.

**Comment by enumag** [comment]
Thanks for the explanation, I'll look into it next year. :-)

**Comment by TomasVotruba** [comment]
Yea, good solutions need time :) 

Next yera, also checkout https://github.com/Symplify/CodingStandard
I'm trying to move to some CLI single line solution like `vendor/bin/checkcs dir [another dir]`. So you don't have to care if it is PHP_CodeSniffer (native or custom rules) or php-cs-fixer.

**Comment by TomasVotruba** [comment]
Not relevant for me anymore.
